# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 10:07
from __future__ import absolute_import
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (u'contenttypes', u'0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'AnonymizedData',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=u'created at')),
                (u'changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=u'changed at')),
                (u'field', models.CharField(max_length=250, verbose_name=u'anonymized field name')),
                (u'object_id', models.TextField(verbose_name=u'related object ID')),
                (u'is_active', models.BooleanField(default=True, verbose_name=u'is active')),
                (u'content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'contenttypes.ContentType',
                                   verbose_name=u'related object content type')),
            ],
            options={
                u'verbose_name': u'anonymized data',
                u'verbose_name_plural': u'anonymized data',
                u'ordering': (u'-created_at',),
            },
        ),
        migrations.CreateModel(
            name=u'LegalReason',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=u'created at')),
                (u'changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=u'changed at')),
                (u'expires_at', models.DateTimeField(db_index=True, verbose_name=u'expires at')),
                (u'tag', models.CharField(blank=True, max_length=100, null=True, verbose_name=u'tag')),
                (u'is_active', models.BooleanField(default=True, verbose_name=u'is active')),
                (u'purpose_slug', models.CharField(max_length=100, verbose_name=u'purpose')),
                (u'source_object_id', models.TextField(verbose_name=u'source object ID')),
                (u'source_object_content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'contenttypes.ContentType',
                                   verbose_name=u'source object content type')),
            ],
            options={
                u'verbose_name': u'legal reason',
                u'verbose_name_plural': u'legal reasons',
                u'ordering': (u'-created_at',),
            },
        ),
        migrations.CreateModel(
            name=u'LegalReasonRelatedObject',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=u'created at')),
                (u'changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=u'changed at')),
                (u'object_id', models.TextField(verbose_name=u'related object ID')),
                (u'content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'contenttypes.ContentType',
                                   verbose_name=u'related object content type')),
                (u'legal_reason',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=u'related_objects',
                                   to=u'gdpr.LegalReason', verbose_name=u'legal reason')),
            ],
            options={
                u'verbose_name': u'legal reason related object',
                u'verbose_name_plural': u'legal reasons related objects',
                u'ordering': (u'-created_at',),
            },
        ),
        migrations.AddField(
            model_name=u'anonymizeddata',
            name=u'expired_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=u'gdpr.LegalReason', verbose_name=u'expired reason'),
        ),
    ]
