# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-25 16:27
from __future__ import absolute_import
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (u'contenttypes', u'0002_remove_content_type_name'),
        (u'gdpr', u'0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'anonymizeddata',
            name=u'content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=u'contenttypes.ContentType',
                                    verbose_name=u'related object content type'),
        ),
        migrations.AlterField(
            model_name=u'anonymizeddata',
            name=u'expired_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=u'gdpr.LegalReason', verbose_name=u'expired reason'),
        ),
        migrations.AlterField(
            model_name=u'legalreason',
            name=u'expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=u'expires at'),
        ),
        migrations.AlterField(
            model_name=u'legalreason',
            name=u'source_object_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=u'contenttypes.ContentType',
                                    verbose_name=u'source object content type'),
        ),
        migrations.AlterField(
            model_name=u'legalreason',
            name=u'source_object_id',
            field=models.TextField(verbose_name=u'source object ID'),
        ),
        migrations.AlterField(
            model_name=u'legalreasonrelatedobject',
            name=u'object_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=u'contenttypes.ContentType',
                                    verbose_name=u'related object content type'),
        ),
        migrations.AlterField(
            model_name=u'legalreasonrelatedobject',
            name=u'object_id',
            field=models.TextField(verbose_name=u'related object ID'),
        ),
        migrations.AlterUniqueTogether(
            name=u'anonymizeddata',
            unique_together=set([(u'content_type', u'object_id', u'field')]),
        ),
        migrations.AlterUniqueTogether(
            name=u'legalreason',
            unique_together=set([(u'purpose_slug', u'source_object_content_type', u'source_object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name=u'legalreasonrelatedobject',
            unique_together=set([(u'legal_reason', u'object_content_type', u'object_id')]),
        ),
    ]
