# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import gdpr.enums


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0006_auto_20190228_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalreason',
            name='state',
            field=models.SmallIntegerField(null=False, blank=False, db_index=True, default=gdpr.enums.LegalReasonState(1), choices=[(1, b'ACTIVE'), (2, b'EXPIRED'), (3, b'DEACTIVATED')]),
        ),
    ]
