# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-17 13:08
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models

import gdpr.enums


class Migration(migrations.Migration):

    dependencies = [
        (u'gdpr', u'0006_auto_20190228_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name=u'legalreason',
            name=u'state',
            field=models.SmallIntegerField(null=False, blank=False, db_index=True, default=gdpr.enums.LegalReasonState(1), choices=[(1, 'ACTIVE'), (2, 'EXPIRED'), (3, 'DEACTIVATED')]),
        ),
    ]
